name: CI
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  LUNTESTS_COLOR: always
jobs:
  build_and_test:
    name: Test - x86_64-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build lunc
        run: cargo build --bin lunc
      - name: Run Compiler Tests
        run: cargo xtask test
      - name: Run Internal Tests
        run: cargo test
      - name: Test compilation of examples
        run: cargo xtask examples
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Formatting check
        run: cargo fmt --check
