name: Typos check
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}-typos
  cancel-in-progress: true
jobs:
  spellcheck:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Check typos
        uses: crate-ci/typos@v1.34.0
        with:
          config: ./typos.toml
